<?php

use Illuminate\Database\Seeder;

class MediaSeeder extends Seeder {
  public function run() {
    $i=1;
    
    $pages = array(
        array('id' => '1104', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'batman-arkham','file_name' => 'batman-1.png'),
        array('id' => '1105', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'arizona-sunshine','file_name' => 'youtube-video-cover-1.png'),
        array('id' => '1106', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'theblu','file_name' => 'theblu-1-1.png'),
        array('id' => '1108', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'superhot','file_name' => 'superhot-1.png'),
        array('id' => '1109', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'serious-sam-fusion-2017','file_name' => 'siruis-sam.png'),
        array('id' => '1117', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'a-lost-room','file_name' => 'a-lost-room.png'),
        array('id' => '1110', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'google-earth-vr','file_name' => 'google-earth.png'),
        array('id' => '1111', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'gnomes-goblins','file_name' => 'gnomes-and-goblins.png'),
        array('id' => '1113', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'tilt-brush','file_name' => 'tilt-brush.png'),
        array('id' => '1115', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'a-escape-vr','file_name' => 'a-escape-vr.png'),
        array('id' => '1116', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'fruit-ninja-vr','file_name' => 'fruit-ninja.png'),
        array('id' => '1118', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'paranormal-activity-the-lost-soul','file_name' => 'paranormal-activity.png'),
        array('id' => '1119', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'raw-data','file_name' => 'raw-data.png'),
        array('id' => '1120', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-lab','file_name' => 'the-lab.png'),
        array('id' => '1121', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-belko-experiment','file_name' => 'the-belko-experiment.png'),
        array('id' => '1122', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'vr-funhouse','file_name' => 'vr-funhouse.png'),
        array('id' => '1123', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'locked-in-vr','file_name' => 'locked-in-vr.png'),
        array('id' => '1124', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'fancy-skiing-vr','file_name' => 'fancy-skiing-vr.png'),
        array('id' => '1156', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'affected-the-manor','file_name' => 'affected.jpg'),
        array('id' => '1157', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'apollo-11','file_name' => 'apollo.jpg'),
        array('id' => '1159', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'araya','file_name' => 'araya.jpg'),
        array('id' => '1162', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'archangel','file_name' => 'archangel.jpg'),
        array('id' => '1163', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-assembly','file_name' => 'the_assembly.jpg'),
        array('id' => '1165', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'audioshield','file_name' => 'audioshield.jpg'),
        array('id' => '1168', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'bartender-vr-simulator','file_name' => 'bartender.jpg'),
        array('id' => '1169', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'bloody-zombies','file_name' => 'bloode_zombie.jpg'),
        array('id' => '1170', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'battlezone','file_name' => 'battlezone.jpg'),
        array('id' => '1171', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'blue-effect','file_name' => 'blue_effect.jpg'),
        array('id' => '1172', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'bowslinger','file_name' => 'bowslinger.jpg'),
        array('id' => '1173', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'boxvr','file_name' => 'boxvr.jpg'),
        array('id' => '1174', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-brookhaven-experiment','file_name' => 'the_brookhaven_experimentt-1_0x260.jpg'),
        array('id' => '1175', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'a-chair-in-a-room-greenwater','file_name' => 'a_chair.jpg'),
        array('id' => '1176', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'chess-ultra','file_name' => 'chess_ultra.jpg'),
        array('id' => '1177', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'climbey','file_name' => 'climbey.jpg'),
        array('id' => '1178', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dead-hungry','file_name' => 'dead_hungry.jpg'),
        array('id' => '1179', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dead-secret','file_name' => 'dead_secret.jpg'),
        array('id' => '1180', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dont-knock-twice','file_name' => 'dont_knock_twice.jpg'),
        array('id' => '1181', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dont-let-go','file_name' => 'dont_et_go.jpg'),
        array('id' => '1182', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dota-2','file_name' => 'dota2.jpg'),
        array('id' => '1183', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'duck-season','file_name' => 'duck_season.jpg'),
        array('id' => '1184', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'eleven-table-tennis-vr','file_name' => 'eleven_table.jpg'),
        array('id' => '1185', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'emily-wants-to-play','file_name' => 'emily.jpg'),
        array('id' => '1186', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'escape-bloody-mary','file_name' => 'escape_bloody.jpg'),
        array('id' => '1187', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'everest-vr','file_name' => 'everest_vr.jpg'),
        array('id' => '1188', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'fast-action-hero','file_name' => 'fast_action_hero.jpg'),
        array('id' => '1189', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'final-soccer-vr','file_name' => 'final_soccer_vr.jpg'),
        array('id' => '1190', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'first-person-tennis','file_name' => 'first_person_tennis.jpg'),
        array('id' => '1191', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'form','file_name' => 'form.jpg'),
        array('id' => '1193', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-gallery-episode-1','file_name' => 'the_gallery_episode_1.jpg'),
        array('id' => '1194', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-gallery-episode-2','file_name' => 'the_gallery_episode_2_0x260.jpg'),
        array('id' => '1195', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-gleam-vr-escape-the-room','file_name' => 'the_gleam_vr_escape_the_room_0x260.jpg'),
        array('id' => '1196', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'gorn','file_name' => 'gorn_0x260.jpg'),
        array('id' => '1197', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'gun-club-vr','file_name' => 'gun_club_vr_0x260.jpg'),
        array('id' => '1198', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'gunheart','file_name' => 'gunheart.jpg'),
        array('id' => '1199', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'i-expect-you-to-die','file_name' => 'i_expect_you_to_die.jpg'),
        array('id' => '1200', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'ironwolf-vr','file_name' => 'iron_wolf.jpg'),
        array('id' => '1201', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'island-359','file_name' => 'island_359.jpg'),
        array('id' => '1202', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'job-simulator','file_name' => 'job_simulator.jpg'),
        array('id' => '1203', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'killing-floor','file_name' => 'killing_floor.jpg'),
        array('id' => '1204', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'la-peri','file_name' => 'la_peri.jpg'),
        array('id' => '1205', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'music-inside','file_name' => 'music_inside.jpg'),
        array('id' => '1206', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'narcosis','file_name' => 'narcosis.jpg'),
        array('id' => '1207', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'nba-2kvr-experience','file_name' => 'nba_2kvr_experience.jpg'),
        array('id' => '1208', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'neurowake','file_name' => 'neurowake.jpg'),
        array('id' => '1209', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'obduction','file_name' => 'obduction.jpg'),
        array('id' => '1210', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'obscura','file_name' => 'obscura.jpg'),
        array('id' => '1212', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'ocean-rift','file_name' => 'ocean_rift.jpg'),
        array('id' => '1213', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'ok-bob','file_name' => 'ok_bob.jpg'),
        array('id' => '1214', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'onward','file_name' => 'onward.jpg'),
        array('id' => '1215', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'overkill-vr','file_name' => 'overkill_vr.jpg'),
        array('id' => '1216', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'pavlov-vr','file_name' => 'pavlov_vr.jpg'),
        array('id' => '1217', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'rise-of-insanity','file_name' => 'rise_of_insanity.jpg'),
        array('id' => '1218', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'robinson-the-journey','file_name' => 'robinson_the_journey.jpg'),
        array('id' => '1219', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'sairento-vr','file_name' => 'sairento_vr.jpg'),
        array('id' => '1221', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'show-must-go-on','file_name' => 'show_must_go_onpsd.jpg'),
        array('id' => '1222', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-solus-project','file_name' => 'the_solus_project.jpg'),
        array('id' => '1223', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'space-bit-attack','file_name' => 'space_bit_attack.jpg'),
        array('id' => '1224', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'sparc','file_name' => 'sparc.jpg'),
        array('id' => '1225', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'sportsbar-vr','file_name' => 'sportsbar_vr.jpg'),
        array('id' => '1226', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'super-vr-trainer','file_name' => 'super_vr_trainer.jpg'),
        array('id' => '1228', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'surgeon-simulator','file_name' => 'surgeon_simulator.jpg'),
        array('id' => '1229', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'svrvive-the-deus-helix','file_name' => 'svrvive_the_deus_helix-1.jpg'),
        array('id' => '1230', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-talos-principle-vr','file_name' => 'the_talos_principle_vr.jpg'),
        array('id' => '1231', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'tethered','file_name' => 'tethered.jpg'),
        array('id' => '1232', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-thrill-of-the-fight','file_name' => 'the_thrill_of_the_fight.jpg'),
        array('id' => '1233', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'time-machine-vr','file_name' => 'time_machine_vr.jpg'),
        array('id' => '1234', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'toon-ocean-vr','file_name' => 'toon_ocean_vr.jpg'),
        array('id' => '1235', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'tornuffalo','file_name' => 'tornuffalo.jpg'),
        array('id' => '1236', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-vanishing-of-ethan-carter','file_name' => 'the_vanishing_of_ethan.jpg'),
        array('id' => '1237', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'vr-varcale-the-room','file_name' => 'vacate.jpg'),
        array('id' => '1238', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-wizards','file_name' => 'the_wizards.jpg'),
        array('id' => '1239', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'zombie-training-simulator','file_name' => 'zombie_training.jpg'),
        array('id' => '1240', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'zomday','file_name' => 'zomday.jpg'),
        array('id' => '1241', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'just-in-time-incorporated','file_name' => 'just_in_time_incorporated.jpg'),
        array('id' => '1242', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'homebound','file_name' => 'homebound.jpg'),
        array('id' => '1243', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'high-noon-vr','file_name' => 'high_noon_vr.jpg'),
        array('id' => '1244', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'henry-the-hamster-handler','file_name' => 'henry_the_hamster.jpg'),
        array('id' => '1245', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'gunship-battle-2-vr','file_name' => 'gunship_battle_2_vr.jpg'),
        array('id' => '1246', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'vr-golf-online','file_name' => 'vr_golf_online.jpg'),
        array('id' => '1247', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'vr-invaders','file_name' => 'vr_invaders.jpg'),
        array('id' => '1248', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'space-pirate-trainer','file_name' => 'space_pirate_trainer.jpg'),
        array('id' => '1249', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'rick-and-morty','file_name' => 'rick_morty_virtual_rickality.jpg'),
        array('id' => '1250', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'protonwar','file_name' => 'proton_war.jpg'),
        array('id' => '1251', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'primal-carnage','file_name' => 'primal_carnage.jpg'),
        array('id' => '1252', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'legendary-hunter-v','file_name' => 'legendary_hunter_vr.jpg'),
        array('id' => '1253', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'gunss-stories-bulletprof-vr','file_name' => 'guns_stories_bulletproof_vr.jpg'),
        array('id' => '1254', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'ghost-town-mine-ride-shootin-gallery','file_name' => 'ghost_town_mine_ride_shooting_gallery.jpg'),
        array('id' => '1255', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'a-fear-of-heights-and-other-things','file_name' => 'a_fear.jpg'),
        array('id' => '1256', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'exorcist-legion-vr','file_name' => 'exorcist_legion_vr.jpg'),
        array('id' => '1257', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'fated-the-silent-oath','file_name' => 'fated_the_silent_oath.jpg'),
        array('id' => '1258', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'eve-valkyrie-warzone','file_name' => 'eve.jpg'),
        array('id' => '1259', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'eagle-flight','file_name' => 'eagle.jpg'),
        array('id' => '1260', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'drunk-of-dead','file_name' => 'drunk_or_dead.jpg'),
        array('id' => '1261', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dream-coaster-vr','file_name' => 'dream_coaster_vr.jpg'),
        array('id' => '1262', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dreadhalls','file_name' => 'dreadhalls.jpg'),
        array('id' => '1263', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'downward-spiral-prologue','file_name' => 'downward.jpg'),
        array('id' => '1264', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'bullet-sorrow-vr','file_name' => 'bullet_sorrow.jpg'),
        array('id' => '1265', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'alice-vr','file_name' => 'alice.jpg'),
        array('id' => '1266', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'adr1ft','file_name' => 'adr1ft.jpg'),
        array('id' => '1267', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'arktika-1','file_name' => 'arktika_1.jpg'),
        array('id' => '1268', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'blade-runner-2049','file_name' => 'blade.jpg'),
        array('id' => '1269', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'blocks','file_name' => 'blocks.jpg'),
        array('id' => '1270', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'coco-vr','file_name' => 'coco.jpg'),
        array('id' => '1271', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dead-and-buried','file_name' => 'dead_and_buried.jpg'),
        array('id' => '1272', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'echo-arena','file_name' => 'echo_arena.jpg'),
        array('id' => '1273', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'edge-of-nowhere','file_name' => 'edge_of_nowhere.jpg'),
        array('id' => '1274', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'face-your-fears','file_name' => 'face_your_fears.jpg'),
        array('id' => '1275', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'final-goalie-football-simulator','file_name' => 'final_golie.jpg'),
        array('id' => '1276', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'killing-floor-incursion','file_name' => 'killing_floor.jpg'),
        array('id' => '1277', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'luckys-tale','file_name' => 'luckys_tale.jpg'),
        array('id' => '1278', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'minecraft','file_name' => 'minecraft.jpg'),
        array('id' => '1279', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'ripcoil','file_name' => 'ripcoil.jpg'),
        array('id' => '1280', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'robo-recall','file_name' => 'robo_recall.jpg'),
        array('id' => '1281', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'rock-band-vr','file_name' => 'rock_band_vr.jpg'),
        array('id' => '1282', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-climb','file_name' => 'the_climb.jpg'),
        array('id' => '1283', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'the-unspoken','file_name' => 'the_unspoken.jpg'),
        array('id' => '1284', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'vr-sports-challenge','file_name' => 'vr_sports_challenge-1.jpg'),
        array('id' => '1285', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'wilson-heart','file_name' => 'wilsons_heart.jpg'),
        array('id' => '1286', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dreamdeck','file_name' => 'dreamdeck.jpg'),
        array('id' => '1287', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'asseto-corsa','file_name' => 'assetto.jpg'),
        array('id' => '1288', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'dirt-rally','file_name' => 'dirt_rally.jpg'),
        array('id' => '1289', 'disk' => 'media',
            'size' => '178469','manipulations' => '[]',
            'custom_properties' => '[]','responsive_images' => '[]',
            'order_column' => '1', 'collection_name' => 'game', 'model_type' => 'App\\Models\\Game', 'model_id' => $i++, 'name' => 'project-cars2','file_name' => 'project_cars2.jpg')
    );

    DB::table("media")->insert($pages);
  }
}
